### ISSUE TITLE
CUDA and torch version

### ISSUE THREAD

**Issue by xieyouchen** [19reborn/PICT_smoke#1]
Thanks for your wonderful project.
Could you please show your the versions of CUDA and torch.
Thank you again.

**Comment by 19reborn** [comment]
Hi, thanks for your interest in our project!
I used `torch==1.13.1` and `CUDA 11.8` on my Ubuntu machine.

**Comment by xieyouchen** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件我已收到，谢谢。
